### ISSUE TITLE
onReady event fired twice (Youtube player loaded twice)

### ISSUE THREAD

**Issue by kospl** [youtube/api-samples#124]
Got this strange issue today that hasn't happened before.

Example of issue: Youtube player on example page https://developers.google.com/youtube/youtube_player_demo loaded twice.

We have same issue also on our webpage where player loaded using Youtube IFrame Player API. After loaded once, player blinks and loaded second time, so `onReady` event triggered twice (but should be just once). Also noticed that `onYouTubeIframeAPIReady` callback works fine and called just once in this case.

**Comment by cesarmejiag** [comment]
I have the same trouble, did someone has a solution to this?

**Comment by kospl** [comment]
@cesarmejiag we found out that on our webpage one script we used (audioEye) was causing `iframes` to reload, we were able to fix it by disabling this script.

**Comment by cesarmejiag** [comment]
Thanks @kospl
