### ISSUE TITLE
upload_video.html (JavaScript) is not working.

### ISSUE THREAD

**Issue by kndol** [youtube/api-samples#197]
I tested JavaScript sample, but I met an error after uploading progress reaches 100%.
Error message is 'Failed to load resource: the server responded with a status of 404 (Not Found)'.

**Comment by kndol** [comment]
my mistake. I fixed ithis.

**Comment by suhao666** [comment]
I seem to be the same as your original question. How do you solve it?

**Comment by suhao666** [comment]
This is my mail box：suhao666333@gmail.com

**Comment by Lucaslah** [comment]
Sometext?

**Comment by suhao666** [comment]
Failed to load resource: the server responded with a status of 404 ()


https://apis.google.com/u/0/_/widget/render/signin?usegapi=1&clientid=1094186313238-79uudgarloef5mem5f1p3kg6da7ku391.apps.googleusercontent.com&cookiepolicy=single_host_origin&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.upload%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube&origin=http%3A%2F%2F192.168.0.103%3A9000&url=http%3A%2F%2F192.168.0.103%3A9000%2Fupload_video.html&gsrc=3p&ic=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.zh_CN.xMHd6MWwi7c.O%2Fam%3DwQE%2Fd%3D1%2Frs%3DAGLTcCN21oSBxUCubBEQauJX-StRbRW21Q%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Conauth%2Conload&id=I0_1560659035983&_gfid=I0_1560659035983&parent=http%3A%2F%2F192.168.0.103%3A9000&pfname=&rpctoken=28556334

**Comment by suhao666** [comment]
This is error

**Comment by suhao666** [comment]
I don't know the cause of the error.Please advise！
