### ISSUE TITLE
Go examples are using depreciated goauth2 library 

### ISSUE THREAD

**Issue by shidel-dev** [youtube/api-samples#23]
The go examples are not up to date. The  the oauth library being used is depreciated.  
See:  https://code.google.com/p/goauth2/

The examples should be using https://github.com/golang/oauth2

**Comment by porjo** [comment]
+1

Import path should be `golang.org/x/oauth2`

**Comment by porjo** [comment]
@iulukaya please reopen this issue. The master branch still contains the old code!
