### ISSUE TITLE
This video has been made private by YouTube

### ISSUE THREAD

**Issue by xandrade** [youtube/api-samples#364]
Team, I'm trying to use the upload_video.py[https://github.com/youtube/api-samples/blob/master/python/upload_video.py] example, the video is flagged as 'This video has been made private by YouTube'.

I have tried to create a new 'web client', new 'credentials json', etc. 

Any advice would be appreciated

**Comment by chenliang0571** [comment]
https://developers.google.com/youtube/v3/docs/videos/insert 

> All videos uploaded via the videos.insert endpoint from unverified API projects created after 28 July 2020 will be restricted to private viewing mode. To lift this restriction, each API project must [undergo an audit](https://support.google.com/youtube/contact/yt_api_form) to verify compliance with the [Terms of Service](https://developers.google.com/youtube/terms/api-services-terms-of-service). Please see the [API Revision History](https://developers.google.com/youtube/v3/revision_history#release_notes_07_28_2020) for more details.

**Comment by DigiCrux** [comment]
Is there a solution to this problem?

**Comment by xandrade** [comment]
Absolutely, I will close this standing issue
