### ISSUE TITLE
Uploaded Video and 0% uploaded

### ISSUE THREAD

**Issue by unnivm** [youtube/api-samples#51]
Hello !,

I have managed to upload a test video of my own to YouTube via YouTube API version 3. But when I checked in my YouTube account I am getting 0% uploaded and I waited for more than 15 minutes though my video is less than 2MB

I was getting the following when I was uploading my video.

Initiation Started
Initiation Completed
Upload Completed!

But it is not calling 
 "case MEDIA_IN_PROGRESS:"

and I am not getting any exception.

Is it because of this, it is not uploading the video or am I missing anything here?

I am using VideoUpload.java to upload video with my keys configured. 

Thanks,
Unni

**Comment by zaasmi** [comment]
we are using upload on vidqo.com working perfectly.
please check if there is some problem please send your link.

**Comment by unnivm** [comment]
The main issue was my video ".mp4" type. Now I changed to ".mov" format  and it is visible immediately after upload. 

One more question: Is there any validation available for type of video we are uploading? 

Thanks

**Comment by unnivm** [comment]
I was able to solve this issue as it is was happening when because of wrong time while encoding my video. Now I can upload .MP4 video
